# Generated by Django 5.2.1 on 2025-05-24 14:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Contact_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('o', 'o-')], max_length=128)),
                ('department', models.CharField(choices=[('cardiology', 'cardiology'), ('cardiology', 'cardiology'), ('cardiology', 'cardiology')], max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient_signup')),
            ],
        ),
    ]
