# Generated by Django 5.2.1 on 2025-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_signup',
            name='password',
            field=models.CharField(default='true', max_length=50),
            preserve_default=False,
        ),
    ]
