# Generated by Django 5.2.1 on 2025-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_superadmin_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin_data',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='superadmin_data',
            name='psw',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
